length:
  max_length_email: 150
  min_length_name: 6
  max_length_name: 50
  min_length_password: 3
email:
  check_mail: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
links:
  links:
  book: "https://www.railstutorial.org/book"
  help: "http://www.railstutorial.org/help"
  railsmain: "http://www.railstutorial.org/"
